
version : '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
    user: root
    depends_on:
      - db
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password1
      MYSQL_DATABASE: internship
    ports:
      - 6033:3306
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
    restart: always
    ports:
      - 81:80
